[package]
name = "oxyl"
version.workspace = true 
edition.workspace = true 
license.workspace = true 
repository.workspace = true 
description = "A fast LaTeX compiler."

[[bin]]
name = "oxyl"
path = "src/main.rs"

[dependencies]
oxyl-lexer = { path = "../oxyl-lexer", version = "0.1.12" }
oxyl-diagnostics = { path = "../oxyl-diagnostics", version = "0.1.12" }
oxyl-parser = { path = "../oxyl-parser", version = "0.1.12" }

