[package]

name = "oxyl-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Parser and AST types for oxyl"

[dependencies]
oxyl-lexer = { path = "../oxyl-lexer", version = "0.1.13" } 
oxyl-diagnostics = { path = "../oxyl-diagnostics", version = "0.1.13" } 
